server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:

        # ---------------------- AUTH SERVICE ----------------------
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        # ---------------------- AI SERVICE ----------------------
        - id: ai-service
          uri: http://localhost:8085
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=0

        # ---------------------- AUDIT SERVICE ----------------------
        - id: audit-service
          uri: http://localhost:8086
          predicates:
            - Path=/audit/**
          filters:
            - StripPrefix=0

        # ---------------------- CASE SERVICE ----------------------
        - id: case-service
          uri: http://localhost:8082
          predicates:
            - Path=/cases/**
          filters:
            - StripPrefix=0

        # ---------------------- DOCUMENT SERVICE ----------------------
        - id: document-service
          uri: http://localhost:8083
          predicates:
            - Path=/documents/**
          filters:
            - StripPrefix=0

        # ---------------------- MEETING SERVICE ----------------------
        - id: meeting-service
          uri: http://localhost:8084
          predicates:
            - Path=/meetings/**
          filters:
            - StripPrefix=0

        # ---------------------- USER VERIFICATION ----------------------
        - id: user-verification-service
          uri: http://localhost:8087
          predicates:
            - Path=/verify/**
          filters:
            - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/jwks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true